sudo: required
services:
    - docker

before_install:
    - docker build -t sesikanth/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true sesikanth/react-test npm run test -- --coverage

after_success:
    - docker build -t sesikanth/multi-client  ./client
    - docker build -t sesikanth/multi-ngnix  ./ngnix
    - docker build -t sesikanth/multi-server  ./server
    - docker build -t sesikanth/multi-worker  ./worker
    - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
    - docker push sesikanth/multi-client
    - docker push sesikanth/multi-ngnix
    - docker push sesikanth/multi-server
    - docker push sesikanth/multi-worker
